export const ADD_LIST_ITEM = "ADD_LIST-ITEM";
export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM";
export const CHANGE_DONE_STATE = "CHANGE_DONE_STATE";
export const HIDE_COMPLATED = "HIDE_COMPLATED";
export const LOCAL_STORE_DATA = "LOCAL_STORE_DATA";
